### ISSUE TITLE
publish fs change to npm

### ISSUE THREAD

**Issue by HaNdTriX** [lanceli/generator-safari-extension#4]
Hey @lanceli 

Could you publish a new Version to npm, that reflects https://github.com/lanceli/generator-safari-extension/commit/aa0b7e0eff16c251a6cd56fb761d46f86ed96c86

**Comment by lanceli** [comment]
v0.0.5 is released.
Thanks buddy.

**Comment by HaNdTriX** [comment]
Awesome! Thanks!
